const http=require('node:http');
const crypto=require('node:crypto');
const PORT=Number(process.env.BINANCE_ONETAP_PORT||18093);
const REST=(process.env.BINANCE_FUTURES_REST_BASE||'https://fapi.binance.com').replace(/\/$/,'');
const API_KEY=process.env.BINANCE_API_KEY||'';
const PRIV=process.env.BINANCE_ED25519_PRIVATE_KEY_PEM||'';
const TG_TOKEN=process.env.TELEGRAM_BOT_TOKEN||'';
const TG_CHAT=String(process.env.TELEGRAM_CHAT_ID||'');
const UPSTREAM=process.env.BINANCE_ONETAP_UPSTREAM||'http://127.0.0.1:18092';
const LIVE=process.env.BINANCE_ONETAP_LIVE==='1';
const RISK_PCT=Number(process.env.BINANCE_RISK_PCT||1);
const MAX_LEV=Number(process.env.BINANCE_MAX_LEVERAGE||20);
const MARGIN_UTIL=Math.min(0.8,Math.max(0.05,Number(process.env.BINANCE_MAX_MARGIN_UTILIZATION||0.45)));
const MAX_OPEN=Math.max(1,Number(process.env.BINANCE_MAX_OPEN_POSITIONS||2));
const TTL=Math.max(30000,Number(process.env.BINANCE_ONETAP_TTL_MS||90000));
const MAX_SIGNAL_AGE=Math.max(TTL,Number(process.env.BINANCE_MAX_SIGNAL_AGE_MS||120000));
const pending=new Map(),notified=new Set(),completed=new Set(),liveTrades=new Map();
let exchangeMeta=new Map(),metaAt=0,accountCache=null,accountAt=0,dualCache=null,dualAt=0,updateOffset=0,tgPollOk=false;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function qs(params){return Object.entries(params).filter(([,v])=>v!==undefined&&v!==null).map(([k,v])=>`${k}=${encodeURIComponent(String(v))}`).join('&')}
function sign(s){const key=crypto.createPrivateKey(PRIV);return crypto.sign(null,Buffer.from(s),key).toString('base64')}
async function signed(method,path,params={}){const p={...params,recvWindow:5000,timestamp:Date.now()},base=qs(p),sig=sign(base),url=`${REST}${path}?${base}&signature=${encodeURIComponent(sig)}`;const r=await fetch(url,{method,headers:{'X-MBX-APIKEY':API_KEY}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data=text}if(!r.ok)throw new Error(`BINANCE_${r.status}_${data?.code??''}_${data?.msg??text}`);return data}
async function tg(method,payload){const r=await fetch(`https://api.telegram.org/bot${TG_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!j.ok)throw new Error(`TG_${method}_${j.error_code}_${j.description}`);return j.result}
function dec(step){const s=String(step);if(s.includes('e-'))return Number(s.split('e-')[1]);return Math.max(0,(s.split('.')[1]||'').replace(/0+$/,'').length)}
function roundStep(v,step){const n=Number(v),s=Number(step);if(!Number.isFinite(n)||!Number.isFinite(s)||s<=0)return n;return Number((Math.round(n/s)*s).toFixed(dec(step)))}
function floorStep(v,step){const n=Number(v),s=Number(step);if(!Number.isFinite(n)||!Number.isFinite(s)||s<=0)return n;return Number((Math.floor((n+1e-12)/s)*s).toFixed(dec(step)))}
function fmt(v,step){return Number(v).toFixed(dec(step))}
function normalizeSymbol(t){const raw=String(t.binanceSymbol||t.instId||t.symbol||t.asset||'').toUpperCase().replace(/[-_/]/g,'');const base=raw.replace(/USDTSWAP$/,'').replace(/USDTPERP$/,'').replace(/USDT$/,'');return base?base+'USDT':''}
function findTickets(x){if(Array.isArray(x))return x;if(!x||typeof x!=='object')return[];for(const k of ['tickets','signals','data','items','open']){if(Array.isArray(x[k]))return x[k];if(x[k]&&typeof x[k]==='object'){const a=findTickets(x[k]);if(a.length)return a}}if(x.id&&x.side&&(x.symbol||x.instId))return[x];return[]}
function safeId(prefix,id){return(prefix+crypto.createHash('sha256').update(String(id)).digest('hex')).slice(0,36)}
async function refreshMeta(force=false){if(!force&&exchangeMeta.size&&Date.now()-metaAt<300000)return;const r=await fetch(`${REST}/fapi/v1/exchangeInfo`);if(!r.ok)throw new Error(`EXCHANGEINFO_${r.status}`);const j=await r.json(),next=new Map();for(const x of j.symbols||[]){if(x.status!=='TRADING'||x.contractType!=='PERPETUAL'||x.quoteAsset!=='USDT')continue;const pf=(x.filters||[]).find(f=>f.filterType==='PRICE_FILTER')||{},lf=(x.filters||[]).find(f=>f.filterType==='LOT_SIZE')||{},nf=(x.filters||[]).find(f=>f.filterType==='MIN_NOTIONAL')||{};if(!pf.tickSize||!lf.stepSize)continue;next.set(x.symbol,{tickSize:pf.tickSize,stepSize:lf.stepSize,minQty:Number(lf.minQty||0),maxQty:Number(lf.maxQty||Infinity),minNotional:Number(nf.notional||5)})}exchangeMeta=next;metaAt=Date.now();console.log('ONETAP_META_READY',JSON.stringify({symbols:next.size}))}
async function account(force=false){if(!force&&accountCache&&Date.now()-accountAt<1000)return accountCache;accountCache=await signed('GET','/fapi/v3/account');accountAt=Date.now();return accountCache}
async function dualMode(force=false){if(!force&&dualCache!==null&&Date.now()-dualAt<60000)return dualCache;const j=await signed('GET','/fapi/v1/positionSide/dual');dualCache=!!j.dualSidePosition;dualAt=Date.now();return dualCache}
async function maxLeverage(symbol){try{const j=await signed('GET','/fapi/v1/leverageBracket',{symbol}),b=Array.isArray(j)?j[0]:j,first=b?.brackets?.[0]?.initialLeverage;return Math.max(1,Math.min(MAX_LEV,Number(first||MAX_LEV)))}catch(e){console.warn('ONETAP_BRACKET_FALLBACK',symbol,String(e.message||e));return MAX_LEV}}
function nonzeroPositions(acc){return(acc.positions||[]).filter(p=>Math.abs(Number(p.positionAmt||0))>0)}
async function preview(ticket,force=false){await refreshMeta();const symbol=normalizeSymbol(ticket),meta=exchangeMeta.get(symbol);if(!meta)return{blocked:'SYMBOL_NOT_USDM_PERP',symbol};const side=String(ticket.side||'').toUpperCase();if(!['BUY','SELL'].includes(side))return{blocked:'BAD_SIDE',symbol};const entry=roundStep(Number(ticket.entry),meta.tickSize),sl=roundStep(Number(ticket.sl),meta.tickSize),tp=roundStep(Number(ticket.tp),meta.tickSize);if(![entry,sl,tp].every(Number.isFinite)||entry<=0)return{blocked:'BAD_PRICES',symbol};if(side==='BUY'&&!(sl<entry&&tp>entry))return{blocked:'INVALID_BUY_LEVELS',symbol};if(side==='SELL'&&!(sl>entry&&tp<entry))return{blocked:'INVALID_SELL_LEVELS',symbol};const acc=await account(force),equity=Number(acc.totalWalletBalance||0),avail=Number(acc.availableBalance||0);if(!(equity>0&&avail>0))return{blocked:'NO_FUTURES_USDT',symbol,equity,avail};const nz=nonzeroPositions(acc);if(nz.some(p=>p.symbol===symbol))return{blocked:'EXISTING_SYMBOL_POSITION',symbol,equity,avail};if(nz.length>=MAX_OPEN)return{blocked:'MAX_OPEN_POSITIONS',symbol,equity,avail,open:nz.length};const dist=Math.abs(entry-sl),riskUsd=equity*(RISK_PCT/100);if(!(dist>0&&riskUsd>0))return{blocked:'BAD_RISK',symbol,equity,avail};const maxLev=await maxLeverage(symbol),rawQty=riskUsd/dist,maxNotional=avail*MARGIN_UTIL*maxLev,qty=floorStep(Math.min(rawQty,maxNotional/entry,meta.maxQty),meta.stepSize),notional=qty*entry;if(!(qty>=meta.minQty)||notional<meta.minNotional)return{blocked:'BELOW_MIN_ORDER',symbol,equity,avail,qty,notional};const leverage=Math.max(1,Math.min(maxLev,Math.ceil(notional/(avail*MARGIN_UTIL)))),margin=notional/leverage,actualRisk=qty*dist;return{blocked:null,id:String(ticket.id),symbol,side,setup:ticket.setup||'',entry,sl,tp,qty,qtyStr:fmt(qty,meta.stepSize),priceStr:fmt(entry,meta.tickSize),slStr:fmt(sl,meta.tickSize),tpStr:fmt(tp,meta.tickSize),equity,avail,riskUsd,actualRisk,notional,leverage,margin,maxLev,meta}}
function ticketText(p,expiresSec){return['⚡ COMBINED EDGE → BINANCE LIVE',`${p.symbol} ${p.side}${p.setup?' | '+p.setup:''}`,`Entry: ${p.entry}`,`SL: ${p.sl}`,`TP: ${p.tp}`,`Qty: ${p.qtyStr}`,`Leverage: ${p.leverage}x`,`Risk: ~${p.actualRisk.toFixed(2)} USDT (${(p.actualRisk/p.equity*100).toFixed(2)}%)`,`Margin: ~${p.margin.toFixed(2)} USDT`,`Futures equity: ${p.equity.toFixed(2)} USDT`,`Expires: ${expiresSec}s`,'','Tap CONFIRM LIVE to submit this exact Combined Edge ticket.'].join('\n')}
async function sendPending(ticket){const id=String(ticket.id||'');if(!id||notified.has(id)||completed.has(id))return;const opened=Date.parse(ticket.openedAt||0);if(Number.isFinite(opened)&&opened>0&&Date.now()-opened>MAX_SIGNAL_AGE){notified.add(id);return}notified.add(id);try{const p=await preview(ticket,false);if(p.blocked){console.log('ONETAP_BLOCKED',JSON.stringify({id,symbol:p.symbol,reason:p.blocked}));return}const token=crypto.randomBytes(10).toString('hex'),expiresAt=Date.now()+TTL,msg=await tg('sendMessage',{chat_id:TG_CHAT,text:ticketText(p,Math.round(TTL/1000)),disable_web_page_preview:true,reply_markup:{inline_keyboard:[[{text:'✅ CONFIRM LIVE',callback_data:`mh:${token}`},{text:'❌ SKIP',callback_data:`ms:${token}`}]]}});pending.set(token,{ticket,id,preview:p,expiresAt,messageId:msg.message_id,locked:false});console.log('ONETAP_PENDING_SENT',JSON.stringify({id,symbol:p.symbol,qty:p.qtyStr,lev:p.leverage,expiresAt}))}catch(e){notified.delete(id);console.error('ONETAP_PENDING_ERR',id,String(e.message||e))}}
async function changeLeverage(p){return signed('POST','/fapi/v1/leverage',{symbol:p.symbol,leverage:p.leverage})}
async function entryOrder(p,hedge){const params={symbol:p.symbol,side:p.side,type:'LIMIT',timeInForce:'IOC',quantity:p.qtyStr,price:p.priceStr,newClientOrderId:safeId('mh_',p.id),newOrderRespType:'RESULT',positionSide:hedge?(p.side==='BUY'?'LONG':'SHORT'):'BOTH'};return signed('POST','/fapi/v1/order',params)}
async function algoOrder(p,kind,hedge){const side=p.side==='BUY'?'SELL':'BUY',params={algoType:'CONDITIONAL',symbol:p.symbol,side,positionSide:hedge?(p.side==='BUY'?'LONG':'SHORT'):'BOTH',type:kind==='SL'?'STOP_MARKET':'TAKE_PROFIT_MARKET',triggerPrice:kind==='SL'?p.slStr:p.tpStr,closePosition:'true',workingType:'CONTRACT_PRICE',priceProtect:'false',clientAlgoId:safeId(kind==='SL'?'mhsl_':'mhtp_',p.id)};return signed('POST','/fapi/v1/algoOrder',params)}
async function emergencyClose(p,hedge,qtyStr){const params={symbol:p.symbol,side:p.side==='BUY'?'SELL':'BUY',type:'MARKET',quantity:qtyStr,newClientOrderId:safeId('mhe_',p.id),newOrderRespType:'RESULT',positionSide:hedge?(p.side==='BUY'?'LONG':'SHORT'):'BOTH'};if(!hedge)params.reduceOnly='true';return signed('POST','/fapi/v1/order',params)}
async function cancelAlgo(symbol,clientAlgoId){try{return await signed('DELETE','/fapi/v1/algoOrder',{symbol,clientAlgoId})}catch{return null}}
async function editMessage(messageId,text){try{return await tg('editMessageText',{chat_id:TG_CHAT,message_id:messageId,text,disable_web_page_preview:true})}catch(e){console.warn('ONETAP_EDIT_ERR',String(e.message||e))}}
async function executePending(item){if(!LIVE)throw new Error('LIVE_GATE_DISABLED');const p=await preview(item.ticket,true);if(p.blocked)throw new Error('BLOCKED_'+p.blocked);const hedge=await dualMode(true);await changeLeverage(p);const order=await entryOrder(p,hedge),executedQty=Number(order.executedQty||0),status=String(order.status||'');if(!(executedQty>0))return{ok:false,reason:`NOT_FILLED_${status||'IOC'}`,p,order};const qtyStr=fmt(executedQty,p.meta.stepSize);let slAlgo=null,tpAlgo=null;try{slAlgo=await algoOrder(p,'SL',hedge);tpAlgo=await algoOrder(p,'TP',hedge)}catch(e){console.error('ONETAP_PROTECTION_FAIL',p.id,String(e.message||e));if(slAlgo)await cancelAlgo(p.symbol,safeId('mhsl_',p.id));if(tpAlgo)await cancelAlgo(p.symbol,safeId('mhtp_',p.id));try{await emergencyClose(p,hedge,qtyStr)}catch(closeErr){console.error('ONETAP_EMERGENCY_CLOSE_FAIL',p.id,String(closeErr.message||closeErr))}throw new Error('PROTECTION_FAIL_POSITION_CLOSED_ATTEMPTED_'+String(e.message||e))}const result={ok:true,p,order,executedQty,avgPrice:Number(order.avgPrice||0),hedge,slAlgo,tpAlgo};liveTrades.set(p.id,{...result,startedAt:Date.now()});monitorTrade(p.id).catch(e=>console.error('ONETAP_MONITOR_ERR',p.id,String(e.message||e)));return result}
async function monitorTrade(id){const t=liveTrades.get(id);if(!t)return;for(let i=0;i<720;i++){await sleep(2000);try{const acc=await account(true),pos=(acc.positions||[]).filter(x=>x.symbol===t.p.symbol),open=pos.some(x=>Math.abs(Number(x.positionAmt||0))>0);if(open)continue;await cancelAlgo(t.p.symbol,safeId('mhsl_',id));await cancelAlgo(t.p.symbol,safeId('mhtp_',id));liveTrades.delete(id);console.log('ONETAP_POSITION_CLOSED',JSON.stringify({id,symbol:t.p.symbol}));try{await tg('sendMessage',{chat_id:TG_CHAT,text:`✅ LIVE POSITION CLOSED\n${t.p.symbol} ${t.p.side}\nProtective sibling order cleaned.`})}catch{}return}catch(e){console.warn('ONETAP_MONITOR_TICK_ERR',id,String(e.message||e))}}}
async function handleCallback(q){const data=String(q.data||''),chat=String(q.message?.chat?.id||'');if(chat!==TG_CHAT)return;const[kind,token]=data.split(':');if(!['mh','ms'].includes(kind)||!token)return;const item=pending.get(token);if(!item){await tg('answerCallbackQuery',{callback_query_id:q.id,text:'This ticket expired or was already handled.',show_alert:true});return}if(item.locked){await tg('answerCallbackQuery',{callback_query_id:q.id,text:'Already processing.',show_alert:false});return}if(Date.now()>item.expiresAt){pending.delete(token);completed.add(item.id);await tg('answerCallbackQuery',{callback_query_id:q.id,text:'Ticket expired.',show_alert:true});await editMessage(item.messageId,'⌛ LIVE TICKET EXPIRED\n'+item.id);return}if(kind==='ms'){item.locked=true;pending.delete(token);completed.add(item.id);await tg('answerCallbackQuery',{callback_query_id:q.id,text:'Skipped.'});await editMessage(item.messageId,`❌ SKIPPED\n${item.preview.symbol} ${item.preview.side}\nNo order was submitted.`);console.log('ONETAP_SKIPPED',item.id);return}item.locked=true;completed.add(item.id);await tg('answerCallbackQuery',{callback_query_id:q.id,text:'Submitting to Binance Futures…'});await editMessage(item.messageId,`⏳ SUBMITTING LIVE\n${item.preview.symbol} ${item.preview.side}\nRechecking balance, position, sizing and leverage…`);try{const r=await executePending(item);pending.delete(token);if(!r.ok){await editMessage(item.messageId,`⚠️ LIVE NOT FILLED\n${r.p.symbol} ${r.p.side}\nIOC entry was not filled. No position opened.`);console.log('ONETAP_NOT_FILLED',JSON.stringify({id:item.id,symbol:r.p.symbol,reason:r.reason}));return}await editMessage(item.messageId,['✅ BINANCE FUTURES LIVE',`${r.p.symbol} ${r.p.side}`,`Filled qty: ${r.executedQty}`,`Avg fill: ${r.avgPrice||'n/a'}`,`Leverage: ${r.p.leverage}x`,`SL: ${r.p.sl}`,`TP: ${r.p.tp}`,`Risk target: ~${r.p.actualRisk.toFixed(2)} USDT`,'SL/TP protection submitted.'].join('\n'));console.log('ONETAP_LIVE_EXECUTED',JSON.stringify({id:item.id,symbol:r.p.symbol,side:r.p.side,qty:r.executedQty,avgPrice:r.avgPrice,lev:r.p.leverage}))}catch(e){pending.delete(token);await editMessage(item.messageId,`❌ LIVE EXECUTION FAILED\n${item.preview.symbol} ${item.preview.side}\n${String(e.message||e).slice(0,300)}\nNo retry was sent automatically.`);console.error('ONETAP_EXEC_ERROR',item.id,String(e.message||e))}}
async function pollTelegram(){if(!TG_TOKEN||!TG_CHAT){console.error('ONETAP_TG_MISSING');return}while(true){try{const updates=await tg('getUpdates',{offset:updateOffset,timeout:20,allowed_updates:['callback_query']});tgPollOk=true;for(const u of updates||[]){updateOffset=Math.max(updateOffset,Number(u.update_id||0)+1);if(u.callback_query)await handleCallback(u.callback_query)}}catch(e){tgPollOk=false;console.error('ONETAP_TG_POLL_ERR',String(e.message||e));await sleep(3000)}}}
async function forward(req,raw){const headers={};for(const[k,v]of Object.entries(req.headers)){if(['host','content-length','connection'].includes(k.toLowerCase())||v==null)continue;headers[k]=Array.isArray(v)?v.join(','):String(v)}return fetch(UPSTREAM+'/ingest',{method:'POST',headers,body:raw})}
setInterval(()=>{const now=Date.now();for(const[token,x]of pending)if(now>x.expiresAt+60000)pending.delete(token)},30000).unref();
const server=http.createServer(async(req,res)=>{try{if(req.method==='GET'&&(req.url==='/health'||req.url==='/status')){const body={ok:true,service:'BINANCE_COMBINED_EDGE_ONETAP',live:LIVE,tgPollOk,pending:pending.size,completed:completed.size,liveTrades:liveTrades.size,riskPct:RISK_PCT,maxLeverage:MAX_LEV,maxMarginUtilization:MARGIN_UTIL,maxOpenPositions:MAX_OPEN};res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify(body))}if(req.method==='POST'&&req.url==='/ingest'){const chunks=[];for await(const c of req)chunks.push(c);const raw=Buffer.concat(chunks);let payload=null;try{payload=JSON.parse(raw.toString('utf8'))}catch{}if(payload){for(const t of findTickets(payload))void sendPending(t)}try{const u=await forward(req,raw),b=Buffer.from(await u.arrayBuffer());res.writeHead(u.status,{'content-type':u.headers.get('content-type')||'application/json'});return res.end(b)}catch(e){res.writeHead(502,{'content-type':'application/json'});return res.end(JSON.stringify({ok:false,error:'upstream_unreachable',detail:String(e.message||e)}))}}res.writeHead(404,{'content-type':'application/json'});res.end(JSON.stringify({ok:false,error:'not_found'}))}catch(e){res.writeHead(500,{'content-type':'application/json'});res.end(JSON.stringify({ok:false,error:String(e.message||e)}))}});
server.listen(PORT,'0.0.0.0',()=>{console.log('BINANCE_ONETAP_READY',JSON.stringify({port:PORT,live:LIVE,ttlMs:TTL,riskPct:RISK_PCT,maxLeverage:MAX_LEV,maxMarginUtilization:MARGIN_UTIL,maxOpenPositions:MAX_OPEN}));refreshMeta().catch(e=>console.error('ONETAP_META_BOOT_ERR',String(e.message||e)));pollTelegram()});