'use strict';
const {spawn}=require('node:child_process');
const PUBLIC_PORT=String(process.env.PORT||8000),ADAPTER_PORT=String(process.env.HUNTER_ADAPTER_PORT||18094);
const ADAPTER_URL=`http://127.0.0.1:${ADAPTER_PORT}/tickets`,INGEST_URL=`http://127.0.0.1:${PUBLIC_PORT}/ingest`,PREVIEW_URL=`http://127.0.0.1:${PUBLIC_PORT}/competition-preview`,LIVE_GATE_URL=`http://127.0.0.1:${PUBLIC_PORT}/hunter-live-gate/observe-candidate`;
const POLL_MS=Math.max(15000,Number(process.env.HUNTER_CONFIRM_POLL_MS||30000)),SEND_MS=Math.max(1200,Number(process.env.HUNTER_CONFIRM_SEND_MS||1800)),MAX_AGE=Math.max(30000,Number(process.env.BINANCE_MAX_SIGNAL_AGE_MS||120000)),TOP_PER_WINDOW=Math.max(1,Number(process.env.HUNTER_TELEGRAM_TOP_PER_WINDOW||3)),WINDOW_MS=Math.max(15000,Number(process.env.HUNTER_TELEGRAM_WINDOW_MS||60000)),PREFLIGHT_N=Math.max(TOP_PER_WINDOW,Math.min(30,Number(process.env.HUNTER_PREFLIGHT_CANDIDATES||12)));
function run(script,extra={},label=script){const p=spawn(process.execPath,[script],{env:{...process.env,...extra},stdio:['ignore','inherit','inherit']});p.on('exit',(c,s)=>{console.error(label+'_EXIT',c,s);if(label==='HUNTER_CONFIRM_LIVE')process.exit(c||1)});return p}
const adapter=run('hunter_onetap_adapter.js',{HUNTER_ADAPTER_PORT:ADAPTER_PORT},'HUNTER_ADAPTER');
const telegram=require.resolve('./telegram_adaptive_fetch_preload.js'),ledger=require.resolve('./real_money_ledger_preload.js'),preflight=require.resolve('./competition_preview_preload.js'),liveGate=require.resolve('./hunter_live_gate_preload_v1.js'),safety=require.resolve('./binance_safety_preload_v1.js');
const gateway=run('binance_onetap_gateway.js',{PORT:PUBLIC_PORT,BINANCE_ONETAP_PORT:PUBLIC_PORT,BINANCE_ONETAP_UPSTREAM:`http://127.0.0.1:${ADAPTER_PORT}`,NODE_OPTIONS:`${process.env.NODE_OPTIONS||''} --require=${ledger} --require=${preflight} --require=${telegram} --require=${liveGate} --require=${safety}`.trim()},'HUNTER_CONFIRM_LIVE');
const sent=new Set();let current=[],polling=false,sending=false,windowStart=Date.now(),windowSent=0;
const n=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d;
function components(t){const hunter=n(t.score||t.edgeScore||t.confidence),base=n(t.baseScore,hunter),rr=n(t._actualNetRR??t.netRR??t.rr??t.riskReward),spread=n(t.spreadBps,8),hurdle=n(t.hurdle,.62),margin=Math.max(0,hunter-hurdle),tf=String(t.timeframe||''),edge=String(t.edge||t.setup||'').toUpperCase(),regime=String(t.regime||'').toUpperCase(),edgeRow=Array.isArray(t.edges)?t.edges.find(x=>String(x.edge||'').toUpperCase()===edge):null,raw=n(edgeRow?.raw,base),fit=n(edgeRow?.regimeFit,1),execution=t.executionGeometry||{},stopBps=n(execution.stopBps,0),costBps=n(t._actualCostBps??execution.estimatedCostBps,12),frictionQuality=Math.max(0,1-Math.min(spread/8,1)),costBuffer=stopBps>0?Math.min(stopBps/Math.max(costBps,1),20)/20:0,tfBonus=tf==='15m'?.012:tf==='5m'?.006:0;return{hunter,base,rr,spread,hurdle,margin,raw,fit,frictionQuality,costBuffer,tfBonus,regime,edge}}
function score(t){const c=components(t);return c.hunter*55+c.base*10+c.margin*35+Math.min(Math.max(c.rr,0),3)*4+c.raw*6+Math.min(Math.max(c.fit,.7),1.3)*3+c.frictionQuality*4+c.costBuffer*2+c.tfBonus}
function fresh(t){const x=Date.parse(t.openedAt||0);return !(Number.isFinite(x)&&x>0&&Date.now()-x>MAX_AGE)}
function symbolKey(t){return String(t.binanceSymbol||t.instId||t.symbol||'').toUpperCase().replace(/[-_/]/g,'')}
function baseRank(tickets){const c=tickets.filter(t=>{const id=String(t.id||'');return id&&!sent.has(id)&&fresh(t)}).sort((a,b)=>score(b)-score(a)),seenSymbols=new Set(),out=[];for(const t of c){const k=symbolKey(t)||String(t.id);if(seenSymbols.has(k))continue;seenSymbols.add(k);out.push(t);if(out.length>=PREFLIGHT_N)break}return out}
async function check(t,phase='PREFLIGHT'){try{const r=await fetch(PREVIEW_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(t),signal:AbortSignal.timeout(7000)}),j=await r.json();if(!r.ok||!j.ok){console.log(phase==='DELIVERY'?'HUNTER_DELIVERY_RECHECK_BLOCK':'HUNTER_PREFLIGHT_BLOCK',JSON.stringify({id:t.id,symbol:t.symbol,reason:j.reason||'HTTP_'+r.status,netRR:j.netRR??null}));return null}return{...t,_actualNetRR:j.netRR,_actualCostBps:j.estimatedRoundTripBps,_previewQty:j.qty,_previewLeverage:j.leverage,_previewNetProfit:j.netProfit}}catch(e){console.warn(phase==='DELIVERY'?'HUNTER_DELIVERY_RECHECK_ERR':'HUNTER_PREFLIGHT_ERR',String(t.id||''),String(e.message||e));return null}}
function observeGate(t){fetch(LIVE_GATE_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(t),signal:AbortSignal.timeout(1500)}).then(r=>{if(!r.ok)console.warn('HUNTER_LIVE_GATE_OBSERVE_HTTP',r.status,String(t.id||''))}).catch(e=>console.warn('HUNTER_LIVE_GATE_OBSERVE_ERR',String(t.id||''),String(e.message||e)))}
async function poll(){if(polling)return;polling=true;try{const r=await fetch(ADAPTER_URL,{signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('ADAPTER_'+r.status);const j=await r.json(),tickets=Array.isArray(j.tickets)?j.tickets:[],raw=baseRank(tickets),checked=[];for(const t of raw){const x=await check(t);if(x)checked.push(x)}current=checked.sort((a,b)=>score(b)-score(a));console.log('HUNTER_OPPORTUNITY_COMPETITION',JSON.stringify({seen:tickets.length,uniqueSymbols:raw.length,preflighted:raw.length,executable:current.length,topPerWindow:TOP_PER_WINDOW,mode:'EXACT_GATEWAY_SYMBOL_WIDE_COMPETITION_RATE_GUARDED',leaders:current.slice(0,5).map(t=>({symbol:t.symbol,rankScore:+score(t).toFixed(5),netRR:+n(t._actualNetRR).toFixed(3),spread:+components(t).spread.toFixed(3),tf:t.timeframe}))}))}catch(e){console.error('HUNTER_CONFIRM_POLL_ERR',String(e.message||e))}finally{polling=false}}
function refreshWindow(){if(Date.now()-windowStart>=WINDOW_MS){windowStart=Date.now();windowSent=0}}
async function sendOne(){if(sending)return;refreshWindow();if(windowSent>=TOP_PER_WINDOW)return;sending=true;try{while(current.length&&(!fresh(current[0])||sent.has(String(current[0].id||''))))current.shift();while(current.length&&windowSent<TOP_PER_WINDOW){const candidate=current.shift();if(!candidate)return;const t=await check(candidate,'DELIVERY');if(!t)continue;const id=String(t.id||'');observeGate(t);const u=await fetch(INGEST_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tickets:[t]}),signal:AbortSignal.timeout(15000)});if(!u.ok)throw Error('INGEST_'+u.status);sent.add(id);windowSent++;console.log('HUNTER_TOP_PICK_SEND',JSON.stringify({id,symbol:t.symbol,rankScore:+score(t).toFixed(5),preflightNetRR:+n(t._actualNetRR).toFixed(3),deliveryRechecked:true,liveGateObserved:true,windowSent,topPerWindow:TOP_PER_WINDOW,currentRemaining:current.length}));break}}catch(e){console.error('HUNTER_CONFIRM_SEND_ERR',String(e.message||e))}finally{sending=false}}
setTimeout(()=>{poll();setInterval(poll,POLL_MS).unref();setInterval(sendOne,SEND_MS).unref()},3000).unref();setInterval(()=>{if(sent.size>5000)sent.clear()},3600000).unref();
function stop(){for(const p of[adapter,gateway])try{p.kill('SIGTERM')}catch{}setTimeout(()=>process.exit(0),500).unref()}process.on('SIGTERM',stop);process.on('SIGINT',stop);
console.log('HUNTER_CONFIRM_LIVE_BOOT',JSON.stringify({live:process.env.BINANCE_ONETAP_LIVE==='1',confirmationRequired:true,source:'Money Hunter',competitionMode:'EXACT_GATEWAY_SYMBOL_WIDE_COMPETITION_RATE_GUARDED',preflightCandidates:PREFLIGHT_N,topPerWindow:TOP_PER_WINDOW,windowMs:WINDOW_MS,adaptiveTelegramCooldown:true,deliveryRecheck:true,liveGateMode:'OBSERVATIONAL_ONLY',liveGateAffectsExecution:false,binanceSafetyPreload:true,stopMarketPriceProtect:process.env.BINANCE_STOP_PRICE_PROTECT==='1',liveGateReport:'/hunter-live-gate/report',realMoneyDashboard:'/real-money',pollMs:POLL_MS,sendMs:SEND_MS,maxAgeMs:MAX_AGE}));
