'use strict';
const http=require('node:http');
const {hunt}=require('./opportunity_hunter_v1');
const {closedMetrics,isFresh}=require('./opportunity_hunter_quality_v1');
const MAX_SIGNAL_AGE=Math.max(30000,Number(process.env.BINANCE_MAX_SIGNAL_AGE_MS||120000));
const {HunterLedger}=require('./opportunity_hunter_ledger_v1');
const {BinanceIpWeightGovernor}=require('./opportunity_hunter_rate_governor_v1');
const ledger=new HunterLedger();
const PORT=Number(process.env.OPPORTUNITY_HUNTER_PORT||19300),BASE='https://fapi.binance.com';
const TOP=Number(process.env.HUNTER_TOP_PAIRS||180),INTERVAL=Number(process.env.HUNTER_SCAN_MS||60000),MIN_SCORE=Number(process.env.HUNTER_MIN_SCORE||.62),MAX_SPREAD=Number(process.env.HUNTER_MAX_SPREAD_BPS||8);
const TFS=(process.env.HUNTER_TIMEFRAMES||'1m,5m,15m').split(',').map(x=>x.trim()).filter(Boolean);
const COST_BPS=Math.max(0,Number(process.env.HUNTER_EST_ROUNDTRIP_COST_BPS||12)),MIN_NET_RR=Math.max(0,Number(process.env.HUNTER_MIN_NET_RR||1.5));
const GROSS_RR=Math.max(1.2,Number(process.env.HUNTER_GROSS_RR||1.8));
const EXCHANGE_INFO_TTL=Math.max(60000,Number(process.env.HUNTER_EXCHANGE_INFO_TTL_MS||3600000));
let exchangeInfoCache={ts:0,allowed:new Set()},lastDiagClosed=-1;
const weightGovernor=new BinanceIpWeightGovernor();
const emptyFunnel=()=>({jobs:0,untradableFiltered:0,badQuote:0,spreadBlocked:0,klineError:0,noMetrics:0,rrBlocked:0,costBlocked:0,edgeBlocked:0,hunterPassed:0,deduped:0,telegramFeed:0,reasons:{},regimes:{},shadowStructureRegimes:{},volatilityBands:{},timeframes:{}});
const state={lastScan:0,scanned:0,inspections:0,candidates:[],errors:[],running:false,funnel:emptyFunnel()};
const finite=(x,d=0)=>Number.isFinite(+x)?+x:d;
const inc=(o,k,n=1)=>o[k]=(o[k]||0)+n;
async function jf(path){await weightGovernor.waitIfNeeded();const ac=new AbortController(),to=setTimeout(()=>ac.abort(),8000);try{const r=await fetch(BASE+path,{signal:ac.signal});const budget=weightGovernor.observe(r);if(budget.paused)console.log('HUNTER_BINANCE_WEIGHT_PAUSE',JSON.stringify(budget));if(!r.ok)throw Error('HTTP_'+r.status);return await r.json()}finally{clearTimeout(to)}}
async function tradableUniverse(){const now=Date.now();if(exchangeInfoCache.allowed.size&&now-exchangeInfoCache.ts<EXCHANGE_INFO_TTL)return exchangeInfoCache.allowed;const x=await jf('/fapi/v1/exchangeInfo'),allowed=new Set((x.symbols||[]).filter(s=>s.contractType==='PERPETUAL'&&s.status==='TRADING'&&s.quoteAsset==='USDT').map(s=>s.symbol));if(!allowed.size)throw Error('EMPTY_USDM_PERP_UNIVERSE');exchangeInfoCache={ts:now,allowed};console.log('HUNTER_UNIVERSE_REFRESH',JSON.stringify({tradable:allowed.size,ttlMs:EXCHANGE_INFO_TTL}));return allowed}
function learning(){const s=ledger.summary(),x={};for(const g of s.leaderboard||[])x[g.edge]={n:g.n,expectancyR:g.expectancyR,winRate:g.winRate};return x}
function shadowStructureRegime(m={}){const er=finite(m.er),mom=Math.abs(finite(m.mom));if(er<=.16)return'RANGE';if(er>=.38&&mom>=8)return'TREND';if(er>=.28&&mom>=14)return'BREAKOUT';return'MIXED'}
function volatilityBand(m={}){const v=finite(m.vol);if(v>=30)return'EXTREME_VOL';if(v>=18)return'HIGH_VOL';return'NORMAL_VOL'}
function closedGroup(field){const groups={};for(const t of ledger.closed||[]){const key=String(t[field]||'UNKNOWN'),g=groups[key]||(groups[key]={key,n:0,wins:0,losses:0,totalR:0});const r=Number(t.r)||0;g.n++;g.totalR+=r;if(r>0)g.wins++;else if(r<0)g.losses++}return Object.values(groups).map(g=>({...g,winRate:g.n?g.wins/g.n:0,expectancyR:g.n?g.totalR/g.n:0})).sort((a,b)=>b.expectancyR-a.expectancyR)}
function shadowRegimeDiagnostics(){return{structure:closedGroup('shadowStructureRegime'),volatility:closedGroup('volatilityBand')}}
function logForwardDiagnostics(){const s=ledger.summary();if(s.closed===lastDiagClosed)return;lastDiagClosed=s.closed;console.log('HUNTER_FORWARD_DIAGNOSTICS',JSON.stringify({open:s.open,closed:s.closed,totalR:s.totalR,exitPolicyShadow:s.exitPolicyShadow,diagnostics:s.diagnostics,shadowRegimeDiagnostics:shadowRegimeDiagnostics()}))}
function geometry(m,side){const e=m.close,structStop=Math.max(m.atr*1.25,e*.0015),cost=e*COST_BPS/1e4;const denom=GROSS_RR-MIN_NET_RR,minStop=denom>0?cost*(1+MIN_NET_RR)/denom:Infinity;if(!(structStop>=minStop))return{blocked:'NET_RR_GEOMETRY_TOO_TIGHT',stop:structStop,minStop,stopBps:structStop/e*1e4,minStopBps:minStop/e*1e4,costBps:COST_BPS};const rr=GROSS_RR;return side==='BUY'?{entry:e,sl:e-structStop,tp:e+structStop*rr,rr,stopBps:structStop/e*1e4,costBps:COST_BPS}:{entry:e,sl:e+structStop,tp:e-structStop*rr,rr,stopBps:structStop/e*1e4,costBps:COST_BPS}}
async function inspect(t,tf,learn,f){const s=t.symbol,b=finite(t.bidPrice),a=finite(t.askPrice);inc(f.timeframes,tf);if(!(b>0&&a>=b)){f.badQuote++;return null}const mid=(a+b)/2;ledger.mark(s,mid);const spread=(a-b)/mid*1e4;if(spread>MAX_SPREAD){f.spreadBlocked++;inc(f.reasons,'SPREAD_TOO_WIDE');return null}let k;try{k=await jf('/fapi/v1/klines?symbol='+encodeURIComponent(s)+'&interval='+encodeURIComponent(tf)+'&limit=61')}catch(e){f.klineError++;inc(f.reasons,'KLINE_ERROR');throw e}const m=closedMetrics(k,tf);if(!m){f.noMetrics++;inc(f.reasons,'INVALID_OR_STALE_CLOSED_BARS');return null}const shadowStructure=shadowStructureRegime(m),volBand=volatilityBand(m);inc(f.shadowStructureRegimes,shadowStructure);inc(f.volatilityBands,volBand);let side=m.mom>=0?'BUY':'SELL',setup='MOMENTUM_CONTINUATION';if(m.close>m.high20){side='BUY';setup='BREAKOUT_RETEST'}else if(m.close<m.low20){side='SELL';setup='BREAKOUT_RETEST'}else if(m.er<.16){side=m.close>(m.high20+m.low20)/2?'SELL':'BUY';setup='RANGE_SWEEP_REVERSION'}else if(m.er>=.38)setup='TREND_PULLBACK_RECLAIM';const g=geometry(m,side);if(g.blocked){f.costBlocked++;inc(f.reasons,g.blocked);return null}const r=hunt({symbol:s,sourceSide:side,sourceSetup:setup,spreadBps:spread,rr:g.rr,entry:g.entry,sl:g.sl,tp:g.tp,market:{mom:m.mom,er:m.er,vol:m.vol}},{minScore:MIN_SCORE,minRR:1.2,maxSpreadBps:MAX_SPREAD,learning:learn});inc(f.regimes,r?.regime||'UNKNOWN');if(r?.action!=='ONE_TAP_CANDIDATE'){for(const reason of r?.reasons||['UNKNOWN']){inc(f.reasons,reason);if(reason==='RR_TOO_LOW')f.rrBlocked++;if(reason==='EDGE_VALUE_TOO_LOW')f.edgeBlocked++}return r}f.hunterPassed++;r.timeframe=tf;r.signalAt=new Date(m.closedAt+1).toISOString();r.candleClosedAt=m.closedAt;r.closedBars=m.closedBars;r.sourceSetup=setup;r.shadowStructureRegime=shadowStructure;r.volatilityBand=volBand;r.marketSnapshot={mom:m.mom,er:m.er,vol:m.vol};r.executionGeometry={estimatedCostBps:COST_BPS,minNetRR:MIN_NET_RR,stopBps:g.stopBps};return r}
async function scan(){if(state.running)return;state.running=true;const f=emptyFunnel();try{const[book,stats,allowed]=await Promise.all([jf('/fapi/v1/ticker/bookTicker'),jf('/fapi/v1/ticker/24hr'),tradableUniverse()]),q=new Map(book.map(x=>[x.symbol,x])),ranked=stats.filter(x=>x.symbol.endsWith('USDT')&&finite(x.quoteVolume)>0).sort((a,b)=>finite(b.quoteVolume)-finite(a.quoteVolume));f.untradableFiltered=ranked.filter(x=>!allowed.has(x.symbol)).length;const u=ranked.filter(x=>allowed.has(x.symbol)).slice(0,TOP).map(x=>q.get(x.symbol)).filter(Boolean),jobs=[];for(const t of u)for(const tf of TFS)jobs.push([t,tf]);f.jobs=jobs.length;const out=[],learn=learning();for(let i=0;i<jobs.length;i+=12){const z=await Promise.all(jobs.slice(i,i+12).map(([x,tf])=>inspect(x,tf,learn,f).catch(e=>{state.errors.unshift({ts:Date.now(),symbol:x.symbol,timeframe:tf,error:String(e.message||e)});return null})));out.push(...z.filter(x=>x?.action==='ONE_TAP_CANDIDATE'))}const best=new Map();for(const t of out){const old=best.get(t.symbol);if(!old||t.score>old.score)best.set(t.symbol,t)}state.candidates=[...best.values()].sort((a,b)=>b.score-a.score).slice(0,30);f.deduped=best.size;f.telegramFeed=state.candidates.length;for(const t of state.candidates)ledger.admit(t);state.scanned=u.length;state.inspections=jobs.length;state.lastScan=Date.now();state.funnel=f;console.log('HUNTER_FUNNEL',JSON.stringify({...f,binanceWeight:weightGovernor.snapshot()}));logForwardDiagnostics()}catch(e){state.errors.unshift({ts:Date.now(),error:String(e.message||e)});state.funnel=f}finally{state.errors=state.errors.slice(0,30);state.running=false}}
function send(res,c,x,ct='application/json; charset=utf-8'){res.writeHead(c,{'content-type':ct,'cache-control':'no-store','access-control-allow-origin':'*'});res.end(ct.startsWith('application/json')?JSON.stringify(x):x)}
function html(){return`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Adaptive Money Hunter</title><style>body{margin:0;background:#07111c;color:#eef5fb;font:15px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.w{max-width:760px;margin:auto;padding:18px}.card{background:#0d1b29;border:1px solid #263e53;border-radius:18px;padding:16px;margin:12px 0}.muted{color:#91a4b5}.n{font-size:22px;font-weight:800}</style><div class="w"><h1>Money Hunter Funnel</h1><div id="x" class="card">Loading...</div></div><script>async function go(){try{const x=await fetch('health?'+Date.now()).then(r=>r.json()),f=x.funnel||{};document.getElementById('x').innerHTML='<div class="n">'+(f.jobs||0)+' checks → '+(f.hunterPassed||0)+' Hunter pass → '+(f.telegramFeed||0)+' Telegram feed</div><p>Universe filtered: '+(f.untradableFiltered||0)+' · Spread blocked: '+(f.spreadBlocked||0)+' · Cost blocked: '+(f.costBlocked||0)+' · Edge blocked: '+(f.edgeBlocked||0)+' · RR blocked: '+(f.rrBlocked||0)+'</p><div class="muted">'+JSON.stringify(f.reasons||{})+'</div>'}catch(e){}}go();setInterval(go,10000)</script>`}
const server=http.createServer((req,res)=>{if(req.url.startsWith('/health'))return send(res,200,{ok:true,version:'ADAPTIVE_MONEY_HUNTER_V4_COST_AWARE',realMoney:false,lastScan:state.lastScan,scanned:state.scanned,inspections:state.inspections,timeframes:TFS,candidates:state.candidates.length,funnel:state.funnel,binanceWeight:weightGovernor.snapshot(),ledger:ledger.summary(),executionGeometry:{estimatedRoundTripCostBps:COST_BPS,minNetRR:MIN_NET_RR,grossRR:GROSS_RR}});if(req.url.startsWith('/funnel'))return send(res,200,{lastScan:state.lastScan,...state.funnel});if(req.url.startsWith('/performance'))return send(res,200,ledger.summary());if(req.url.startsWith('/diagnostics')){const s=ledger.summary();return send(res,200,{open:s.open,closed:s.closed,totalR:s.totalR,exitPolicyShadow:s.exitPolicyShadow,diagnostics:s.diagnostics,shadowRegimeDiagnostics:shadowRegimeDiagnostics()})}if(req.url.startsWith('/tickets'))return send(res,200,{version:'ADAPTIVE_MONEY_HUNTER_V4_COST_AWARE',realMoney:false,execution:'USER_CONFIRM_REQUIRED',lastScan:state.lastScan,scanned:state.scanned,inspections:state.inspections,timeframes:TFS,tickets:state.candidates.filter(t=>isFresh(t,MAX_SIGNAL_AGE))});if(req.url==='/'||req.url.startsWith('/?'))return send(res,200,html(),'text/html; charset=utf-8');return send(res,404,{ok:false,error:'not_found'})});
server.listen(PORT,()=>{console.log('ADAPTIVE_MONEY_HUNTER_V4_COST_AWARE_READY',JSON.stringify({port:PORT,realMoney:false,topPairs:TOP,timeframes:TFS,interval:INTERVAL,forwardLearning:true,minFloor:MIN_SCORE,estimatedRoundTripCostBps:COST_BPS,minNetRR:MIN_NET_RR,grossRR:GROSS_RR,tradableUniverseFilter:true,closedBarsOnly:true,signalClock:'CANDLE_CLOSE',maxSignalAgeMs:MAX_SIGNAL_AGE,shadowStructureDiagnostics:true,binanceWeightGovernor:weightGovernor.snapshot()}));scan();setInterval(scan,INTERVAL).unref()});
