'use strict';
const http=require('node:http');
const PORT=Number(process.env.PORT||8000);
const HUNTER_URL=process.env.PORTFOLIO_SHADOW_HUNTER_URL||'https://xauusd-live-app-production.up.railway.app/hunter/tickets';
const REAL_URL=process.env.PORTFOLIO_SHADOW_REAL_URL||'https://crypto-signal-publisher-production.up.railway.app/real-money/positions';
const BOOK_URL='https://fapi.binance.com/fapi/v1/ticker/bookTicker';
const POLL_MS=Math.max(15000,Number(process.env.PORTFOLIO_SHADOW_POLL_MS||30000));
const CAP=Math.max(1,Number(process.env.PORTFOLIO_SHADOW_CAP||8));
const TOP_N=Math.max(1,Math.min(30,Number(process.env.PORTFOLIO_SHADOW_TOP_N||12)));
const TTL_MS=Math.max(15*60*1000,Number(process.env.PORTFOLIO_SHADOW_TTL_MS||6*60*60*1000));
const active=new Map(),closed=[];let lastPoll=0,lastError='',lastState={openCount:0,openSymbols:[],candidateCount:0};
const n=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d;
const sym=x=>String(x||'').toUpperCase().replace(/[-_/]/g,'');
async function jf(url){const r=await fetch(url,{headers:{'cache-control':'no-cache'},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('HTTP_'+r.status+' '+url);return r.json()}
function openInfo(j){const ts=Array.isArray(j?.trades)?j.trades:[];const os=new Set(ts.filter(t=>t?.isOpen===true||String(t?.status||'').toUpperCase()==='OPEN').map(t=>sym(t.symbol||t.binanceSymbol||t.instId)).filter(Boolean));let c=n(j?.open,NaN);if(!Number.isFinite(c))c=os.size;return{count:c,symbols:os}}
function rAt(t,p){const risk=Math.abs(n(t.entry)-n(t.sl))||1;return t.side==='BUY'?(p-n(t.entry))/risk:(n(t.entry)-p)/risk}
function key(t){return[sym(t.symbol),String(t.side||''),String(t.timeframe||'UNKNOWN')].join('|')}
function stats(xs){const sum=xs.reduce((s,t)=>s+n(t.r),0),w=xs.filter(t=>n(t.r)>0).length,l=xs.filter(t=>n(t.r)<0).length;return{n:xs.length,wins:w,losses:l,breakeven:xs.length-w-l,totalR:sum,winRate:xs.length?w/xs.length:0,expectancyR:xs.length?sum/xs.length:0}}
function groups(field){const m={};for(const t of closed){const k=String(t[field]||'UNKNOWN');(m[k]||(m[k]=[])).push(t)}return Object.entries(m).map(([key,xs])=>({key,...stats(xs)})).sort((a,b)=>b.expectancyR-a.expectancyR)}
function summary(){return{mode:'READ_ONLY_PORTFOLIO_SLOT_SHADOW',liveChanges:false,cap:CAP,topN:TOP_N,pollMs:POLL_MS,lastPoll,lastError,lastState,active:active.size,closed:closed.length,cohorts:groups('cohort'),timeframes:groups('timeframe'),sides:groups('side'),rankBuckets:groups('rankBucket'),recent:closed.slice(-30).reverse()}}
function mark(book,now){for(const [k,t] of active){const b=book.get(sym(t.symbol));if(!b)continue;const p=(n(b.bidPrice)+n(b.askPrice))/2;if(!(p>0))continue;const cur=rAt(t,p);t.mfeR=Math.max(n(t.mfeR),cur);t.maeR=Math.min(n(t.maeR),cur);let outcome='';if(t.side==='BUY'){if(p<=n(t.sl))outcome='SL';else if(p>=n(t.tp))outcome='TP'}else{if(p>=n(t.sl))outcome='SL';else if(p<=n(t.tp))outcome='TP'}if(!outcome&&now-t.openedAt>=TTL_MS)outcome='TIME';if(!outcome)continue;let r=cur;if(outcome==='TP')r=n(t.rr,cur);if(outcome==='SL')r=-1;closed.push({...t,status:'CLOSED',closedAt:now,outcome,exit:p,r});active.delete(k)}if(closed.length>5000)closed.splice(0,closed.length-5000)}
async function poll(){try{const [hj,rj,bj]=await Promise.all([jf(HUNTER_URL+'?t='+Date.now()),jf(REAL_URL+'?t='+Date.now()),jf(BOOK_URL)]),oi=openInfo(rj),book=new Map((Array.isArray(bj)?bj:[]).map(x=>[sym(x.symbol),x])),now=Date.now();mark(book,now);const tickets=(Array.isArray(hj?.tickets)?hj.tickets:[]).filter(t=>n(t.entry)>0&&n(t.sl)>0&&n(t.tp)>0&&['BUY','SELL'].includes(String(t.side))).sort((a,b)=>n(b.score)-n(a.score)).slice(0,TOP_N);for(let i=0;i<tickets.length;i++){const t=tickets[i],s=sym(t.symbol);if(!s||oi.symbols.has(s))continue;const k=key(t);if(active.has(k))continue;const cohort=oi.count>=CAP?'BLOCKED_CAP':'SLOT_AVAILABLE',rank=i+1,rankBucket=rank<=3?'TOP3':rank<=6?'R4_6':'R7_PLUS';active.set(k,{symbol:s,side:String(t.side),timeframe:String(t.timeframe||'UNKNOWN'),edge:String(t.edge||t.setup||''),score:n(t.score),entry:n(t.entry),sl:n(t.sl),tp:n(t.tp),rr:n(t.rr),spreadBps:n(t.spreadBps),cohort,rank,rankBucket,openedAt:now,mfeR:0,maeR:0,status:'OPEN',portfolioOpenAtAdmission:oi.count})}lastPoll=now;lastError='';lastState={openCount:oi.count,openSymbols:[...oi.symbols],candidateCount:tickets.length};console.log('PORTFOLIO_SLOT_SHADOW',JSON.stringify({openCount:oi.count,active:active.size,closed:closed.length,cohorts:groups('cohort')}))}catch(e){lastPoll=Date.now();lastError=String(e.message||e);console.error('PORTFOLIO_SLOT_SHADOW_ERR',lastError)}}
const server=http.createServer((req,res)=>{const body=req.url.startsWith('/summary')?summary():req.url.startsWith('/health')?{ok:true,lastPoll,lastError,active:active.size,closed:closed.length}:null;if(!body){res.writeHead(404,{'content-type':'application/json'});return res.end(JSON.stringify({ok:false}))}res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(body))});
server.listen(PORT,()=>{console.log('PORTFOLIO_SLOT_SHADOW_READY',JSON.stringify({port:PORT,cap:CAP,topN:TOP_N,pollMs:POLL_MS,liveChanges:false}));poll();setInterval(poll,POLL_MS).unref()});
