'use strict';
const http=require('node:http');
const {spawn}=require('node:child_process');
const PORT=Number(process.env.PORT||8000),INNER=8001;
const BINANCE=(process.env.BINANCE_PUBLIC_REST||'https://fapi.binance.com').replace(/\/$/,'');
const FEE=Number(process.env.SHADOW_ENTRY_FEE_BPS||2),EXIT_FEE=Number(process.env.SHADOW_EXIT_FEE_BPS||5),SLIP=Number(process.env.SHADOW_EXIT_SLIPPAGE_BPS||1),FRICTION=FEE+EXIT_FEE+SLIP;
const TTL=Math.max(30000,Number(process.env.SHADOW_ENTRY_TTL_MS||90000)),RISK=Number(process.env.SHADOW_RISK_PCT||1),MAX_OPEN=Math.max(1,Number(process.env.SHADOW_MAX_OPEN||8)),START=Number(process.env.SHADOW_START_BALANCE||1000),START_MS=Date.now();
const child=spawn(process.execPath,['validation_server_v5_adaptive_lab.js'],{env:{...process.env,PORT:String(INNER)},stdio:['ignore','inherit','inherit']});
child.on('exit',(c,s)=>console.error('INNER_V5_EXIT',c,s));
const P=[
{id:'TREND_PURE',name:'Trend Pure',kind:'pure',allow:['TREND'],mf:.18,rr:1.35,min:25,sr:.10},
{id:'BREAKOUT_PURE',name:'Breakout Pure',kind:'pure',allow:['BREAKOUT'],mf:.15,rr:1.50,min:30,sr:.08},
{id:'RANGE_PURE',name:'Range Pure',kind:'pure',allow:['RANGE'],mf:.10,rr:1.80,min:60,sr:.06},
{id:'TREND_BREAKOUT_FUSION',name:'Trend × Breakout Fusion',kind:'fusion',allow:['TREND','BREAKOUT'],mf:.16,rr:1.45,min:25,sr:.08},
{id:'RANGE_TREND_FUSION',name:'Range × Trend Fusion',kind:'fusion',allow:['RANGE','TREND'],mf:.13,rr:1.55,min:35,sr:.07},
{id:'ALL_STYLE_FUSION',name:'All-Style Fusion',kind:'fusion',mf:.14,rr:1.55,min:30,sr:.08},
{id:'SPEED_FUSION',name:'Speed Fusion',kind:'fusion',mf:.20,rr:1.25,min:20,sr:.12},
{id:'DEFENSIVE_FUSION',name:'Defensive Fusion',kind:'fusion',mf:.09,rr:1.90,min:60,sr:.05},
{id:'REGIME_SWITCHER',name:'Regime Switcher',kind:'regime',mf:.15,rr:1.45,min:25,sr:.09,regime:true},
{id:'REGIME_FUSION',name:'Adaptive Regime Fusion',kind:'regime',mf:.16,rr:1.40,min:20,sr:.10,regime:true,adaptive:true},
{id:'CONSENSUS_3',name:'3-Brain Consensus',kind:'ensemble',synth:'CONS',votes:3},
{id:'CONSENSUS_5',name:'5-Brain Consensus',kind:'ensemble',synth:'CONS',votes:5},
{id:'ELITE_FUSION',name:'Elite Fusion',kind:'ensemble',synth:'ELITE'},
{id:'META_FUSION',name:'Meta Fusion',kind:'meta',synth:'META'}];
const BASE=P.filter(x=>!x.synth),VOTERS=BASE.map(x=>x.id),ELITE=['DEFENSIVE_FUSION','REGIME_SWITCHER','REGIME_FUSION','TREND_BREAKOUT_FUSION','RANGE_PURE'];
const S={brains:new Map(),meta:new Map(),metaAt:0,reg:new Map(),errors:[],seen:new Set(),fresh:new Set()};
const mk=p=>({...p,seen:new Set(),pending:new Map(),open:new Map(),closed:[],passed:0,rejected:0,balance:START,peak:START,dd:0,reasons:{},born:Date.now()});for(const p of P)S.brains.set(p.id,mk(p));
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
function out(res,c,x){res.writeHead(c,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(x));}
function fail(w,e){S.errors.push({t:Date.now(),w,e:String(e?.message||e)});S.errors=S.errors.filter(x=>Date.now()-x.t<86400000);console.error('OPEN_ARENA_ERR',w,e?.message||e)}
function tickets(x){if(Array.isArray(x))return x;if(!x||typeof x!=='object')return[];for(const k of['tickets','signals','data','items','open']){if(Array.isArray(x[k]))return x[k];if(x[k]&&typeof x[k]==='object'){const a=tickets(x[k]);if(a.length)return a}}if(x.id&&x.side&&(x.symbol||x.instId))return[x];return[]}
function sym(t){const r=String(t.binanceSymbol||t.instId||t.symbol||t.asset||'').toUpperCase().replace(/[-_/]/g,''),b=r.replace(/USDTSWAP$/,'').replace(/USDTPERP$/,'').replace(/USDT$/,'');return b?b+'USDT':''}
function fam(x){x=String(x||'').toUpperCase();if(x.includes('RANGE')||x.includes('MEAN_REVERSION')||x.includes('SWEEP'))return'RANGE';if(x.includes('BREAKOUT')||x.includes('RETEST'))return'BREAKOUT';if(x.includes('TREND')||x.includes('PULLBACK')||x.includes('RECLAIM'))return'TREND';return'OTHER'}
function geom(t){const e=+t.entry,s=+t.sl,p=+t.tp,d=String(t.side||'').toUpperCase();if(![e,s,p].every(Number.isFinite)||e<=0)return null;if(d==='BUY'&&!(s<e&&p>e)||d==='SELL'&&!(s>e&&p<e)||!['BUY','SELL'].includes(d))return null;const rb=Math.abs(e-s)/e*1e4,wb=Math.abs(p-e)/e*1e4;if(!(rb>0&&wb>0))return null;return{e,s,p,d,rb,wb,fr:FRICTION/rb,nrr:(wb-FRICTION)/(rb+FRICTION)}}
async function meta(){if(S.meta.size&&Date.now()-S.metaAt<3e5)return;const r=await fetch(BINANCE+'/fapi/v1/exchangeInfo'),j=await r.json(),m=new Map();for(const x of j.symbols||[]){if(x.status!=='TRADING'||x.contractType!=='PERPETUAL'||x.quoteAsset!=='USDT')continue;const f=(x.filters||[]).find(q=>q.filterType==='PRICE_FILTER');if(f)m.set(x.symbol,+f.tickSize)}S.meta=m;S.metaAt=Date.now()}
async function book(s){const r=await fetch(BINANCE+'/fapi/v1/ticker/bookTicker?symbol='+s),x=await r.json();return{b:+x.bidPrice,a:+x.askPrice}}
async function price(s){const r=await fetch(BINANCE+'/fapi/v1/ticker/price?symbol='+s),x=await r.json();return+x.price}
async function regime(s){const c=S.reg.get(s);if(c&&Date.now()-c.t<18e4)return c;try{const r=await fetch(BINANCE+'/fapi/v1/klines?symbol='+s+'&interval=5m&limit=48'),k=await r.json(),cs=k.map(x=>+x[4]);let path=0;for(let i=1;i<cs.length;i++)path+=Math.abs(cs[i]-cs[i-1]);const er=path?Math.abs(cs.at(-1)-cs[0])/path:0,rs=[];for(let i=1;i<cs.length;i++)rs.push(Math.log(cs[i]/cs[i-1])*1e4);const av=rs.reduce((a,b)=>a+b,0)/(rs.length||1),vol=Math.sqrt(rs.reduce((a,x)=>a+(x-av)**2,0)/Math.max(1,rs.length-1));let l='MIXED';if(er>=.35)l='TREND';else if(er<=.18)l='RANGE';else if(vol>=35)l='VOLATILE';const z={t:Date.now(),l,er,vol};S.reg.set(s,z);return z}catch(e){fail('regime',e);return{t:Date.now(),l:'UNKNOWN'}}}
function regOK(f,r){if(!r||['UNKNOWN','MIXED'].includes(r.l))return true;if(r.l==='TREND')return['TREND','BREAKOUT','OTHER'].includes(f);if(r.l==='RANGE')return['RANGE','OTHER'].includes(f);if(r.l==='VOLATILE')return['BREAKOUT','TREND','OTHER'].includes(f);return true}
function gate(p,t,sp,r){const f=fam(t.setup);if(p.allow&&!p.allow.includes(f))return{pass:false,why:'FAMILY'};const g=geom(t);if(!g)return{pass:false,why:'GEOMETRY'};if(p.regime&&!regOK(f,r))return{pass:false,why:'REGIME'};let mf=p.mf,rr=p.rr,mn=p.min,sr=p.sr;if(p.adaptive){if(r?.l==='TREND'){mf+=.02;rr-=.1}else if(r?.l==='RANGE'){mf-=.02;rr+=.15;mn=Math.max(mn,50)}else if(r?.l==='VOLATILE'){mn=Math.max(mn,50);sr=Math.min(sr,.07)}}const spr=Number.isFinite(sp)?sp/g.rb:null;if(g.rb<mn)return{pass:false,why:'NARROW'};if(g.fr>mf)return{pass:false,why:'COST'};if(g.nrr<rr)return{pass:false,why:'RR'};if(!Number.isFinite(spr)||spr>sr)return{pass:false,why:'SPREAD'};return{pass:true,why:'PASS',f,...g,spr}}
function has(b,s){for(const x of b.pending.values())if(x.s===s)return true;for(const x of b.open.values())if(x.s===s)return true;return false}
function round(v,step){return Math.round(v/step)*step}
async function track(b,t,g){const id=String(t.id||'');if(!id||b.seen.has(id))return;b.seen.add(id);if(!g.pass){b.rejected++;b.reasons[g.why]=(b.reasons[g.why]||0)+1;return}b.passed++;const s=sym(t);if(!s||has(b,s)||b.pending.size+b.open.size>=MAX_OPEN)return;await meta();const st=S.meta.get(s);if(!st)return;const d=String(t.side).toUpperCase(),e=round(+t.entry,st),sl=round(+t.sl,st),tp=round(+t.tp,st);if(d==='BUY'&&!(sl<e&&tp>e)||d==='SELL'&&!(sl>e&&tp<e))return;b.pending.set(id,{id,s,d,e,sl,tp,setup:String(t.setup||''),until:Date.now()+TTL})}
function close(b,x,why){const dist=Math.abs(x.e-x.sl),q=SLIP/1e4,ex=why==='TP'?(x.d==='BUY'?x.tp*(1-q):x.tp*(1+q)):(x.d==='BUY'?x.sl*(1-q):x.sl*(1+q)),gross=x.d==='BUY'?(ex-x.e)/dist:(x.e-ex)/dist,fee=(x.e*FEE/1e4+Math.abs(ex)*EXIT_FEE/1e4)/dist,nr=gross-fee;b.closed.push({...x,why,nr});b.open.delete(x.id);b.balance*=1+RISK/100*nr;b.peak=Math.max(b.peak,b.balance);b.dd=Math.max(b.dd,(b.peak-b.balance)/b.peak*100)}
function st(b){const c=b.closed,n=c.length,w=c.filter(x=>x.nr>0).length,net=c.reduce((a,x)=>a+x.nr,0),pos=c.filter(x=>x.nr>0).reduce((a,x)=>a+x.nr,0),neg=Math.abs(c.filter(x=>x.nr<0).reduce((a,x)=>a+x.nr,0)),ex=n?net/n:null,pf=neg?pos/neg:(pos?99:null);let lcb=null;if(n>1){const sd=Math.sqrt(c.reduce((a,x)=>a+(x.nr-ex)**2,0)/(n-1));lcb=ex-1.282*sd/Math.sqrt(n)}const proven=n>=50&&ex>.1&&pf>1.15&&b.dd<10&&lcb>0,prom=n>=20&&ex>.1&&pf>1.15&&b.dd<10,fail=n>=20&&(ex<=0||pf<.9||b.dd>=15),status=proven?'PROVEN':fail?'FAILING':prom?'PROMISING':'LEARNING',proof=100*(.4*clamp(n/50)+.22*(ex==null?0:clamp((ex+.1)/.25))+.14*(pf==null?0:clamp((pf-.8)/.5))+.1*clamp((15-b.dd)/10)+.14*(lcb==null?0:clamp((lcb+.05)/.15))),score=n<5?-999:(lcb??ex??-9)*Math.min(1,n/30)+.025*Math.log1p(n)-Math.max(0,b.dd-10)*.02;return{id:b.id,name:b.name,kind:b.kind,trades:n,wins:w,expectancy:ex,profitFactor:pf,maxDDPct:b.dd,lcb90:lcb,status,proofProgress:proof,evidenceScore:score,balance:b.balance}}
function extraRank(){return[...S.brains.values()].map(st).sort((a,b)=>b.evidenceScore-a.evidenceScore||b.proofProgress-a.proofProgress)}
function metaPick(){return extraRank().filter(x=>!['CONSENSUS_3','CONSENSUS_5','ELITE_FUSION','META_FUSION'].includes(x.id)&&x.trades>=10&&x.status!=='FAILING')[0]?.id||'ALL_STYLE_FUSION'}
async function ingestLocal(payload){const a=tickets(payload).filter(x=>x?.combinedSelected===true&&x?.id);if(!a.length)return;await meta();for(const t of a){const id=String(t.id),op=Date.parse(t.openedAt||0),fresh=!(op>0&&op<START_MS);S.seen.add(id);if(fresh)S.fresh.add(id);const s=sym(t);let bk=null,r=null;try{bk=await book(s);r=await regime(s)}catch(e){fail('market',e)}const sp=bk&&bk.a>0&&bk.b>0?(bk.a-bk.b)/((bk.a+bk.b)/2)*1e4:null,base=new Map();for(const p of BASE){const b=S.brains.get(p.id);if(b.seen.has(id))continue;const g=fresh?gate(p,t,sp,r):{pass:false,why:'PRE'};base.set(p.id,g);await track(b,t,g)}for(const p of P.filter(x=>x.synth)){const b=S.brains.get(p.id);if(b.seen.has(id))continue;let g;if(!fresh)g={pass:false,why:'PRE'};else if(p.synth==='CONS'){const v=VOTERS.filter(k=>base.get(k)?.pass).length;g={pass:v>=p.votes,why:'VOTES',v}}else if(p.synth==='ELITE'){const v=ELITE.filter(k=>base.get(k)?.pass).length;g={pass:v>=3,why:'ELITE',v}}else{const k=metaPick();g=base.get(k)||{pass:false,why:'META_EMPTY'}}await track(b,t,g)}}}
async function poll(){while(true){try{const ps=new Set(),os=new Set();for(const b of S.brains.values()){for(const x of b.pending.values())ps.add(x.s);for(const x of b.open.values())os.add(x.s)}const bs=new Map(),px=new Map();await Promise.all([...ps].map(async s=>{try{bs.set(s,await book(s))}catch(e){}}));await Promise.all([...os].map(async s=>{try{px.set(s,await price(s))}catch(e){}}));for(const b of S.brains.values()){for(const[id,x]of[...b.pending]){if(Date.now()>x.until){b.pending.delete(id);continue}const q=bs.get(x.s);if(q&&(x.d==='BUY'?q.a<=x.e:q.b>=x.e)){b.pending.delete(id);b.open.set(id,x)}}for(const[id,x]of[...b.open]){const p=px.get(x.s);if(!Number.isFinite(p))continue;if(x.d==='BUY'){if(p<=x.sl)close(b,x,'SL');else if(p>=x.tp)close(b,x,'TP')}else{if(p>=x.sl)close(b,x,'SL');else if(p<=x.tp)close(b,x,'TP')}}}}catch(e){fail('poll',e)}await sleep(1000)}}
async function inner(path,init){const r=await fetch('http://127.0.0.1:'+INNER+path,init);return{status:r.status,text:await r.text()}}
async function combined(){let core={brains:[],brainCount:0,generation:0,sourceFresh:0};try{core=JSON.parse((await inner('/lab.json')).text)}catch{}const all=[...(core.brains||[]),...extraRank()].sort((a,b)=>(b.evidenceScore??-999)-(a.evidenceScore??-999)||(b.proofProgress??0)-(a.proofProgress??0));const leader=all.find(x=>x.id!=='RAW_CONTROL'&&x.trades>=5)||all.find(x=>x.id!=='RAW_CONTROL')||null;return{status:all.some(x=>x.status==='PROVEN')?'EDGE_PROVEN':'HUNTING',version:'OPEN_EDGE_ARENA_V2',liveTrading:false,leader,brains:all,brainCount:all.length,coreBrains:core.brainCount||0,fusionBrains:S.brains.size,generation:core.generation||0,sourceFresh:Math.max(core.sourceFresh||0,S.fresh.size),metaLeader:metaPick(),errors24h:S.errors.length}}
function page(){return`<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>Open Edge Arena</title><style>:root{color-scheme:dark}body{margin:0;background:#07101a;color:#eef5ff;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}.w{max-width:1180px;margin:auto;padding:16px}.m{color:#8da2bb;font-size:12px}.g{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.c{background:#101c2a;border:1px solid #25384c;border-radius:15px;padding:13px}.v{font-size:21px;font-weight:800}.r{display:grid;grid-template-columns:1.7fr .55fr .7fr .7fr .7fr;gap:6px;padding:9px 0;border-bottom:1px solid #24364a;font-size:12px}.good{color:#6ee7a8}.bad{color:#ff8f8f}@media(min-width:760px){.g{grid-template-columns:repeat(4,1fr)}}h1{margin:4px 0 2px}h2{font-size:16px}</style><div class=w><div class=m>MONEY HUNTER · BINANCE-REALISTIC SHADOW</div><h1>OPEN EDGE ARENA</h1><div class=m>Original challengers + pure specialists + fusion brains + regime brains + consensus + meta · Real money OFF</div><div id=g class=g style="margin-top:14px"></div><h2>Overall leaderboard</h2><div class=c><div class="r m"><b>Brain</b><b>Trades</b><b>Exp</b><b>PF</b><b>Proof</b></div><div id=b></div></div></div><script>const f=x=>x==null?'—':Number(x).toFixed(2);async function go(){const x=await fetch('/arena.json?'+Date.now()).then(r=>r.json()),L=x.leader||{};g.innerHTML=[['#1',L.name||'Learning'],['Exp',L.expectancy==null?'—':f(L.expectancy)+'R'],['Brains',x.brainCount],['Fresh',x.sourceFresh],['Core',x.coreBrains],['Fusion',x.fusionBrains],['Meta follows',x.metaLeader],['Generation',x.generation]].map(z=>'<div class=c><div class=m>'+z[0]+'</div><div class=v>'+z[1]+'</div></div>').join('');b.innerHTML=x.brains.filter(q=>q.id!=='RAW_CONTROL').map((q,i)=>'<div class=r><div><b>#'+(i+1)+' '+q.name+'</b><div class=m>'+q.kind+' · '+q.status+'</div></div><div>'+q.trades+'</div><div class="'+(q.expectancy>0?'good':q.expectancy<0?'bad':'')+'">'+f(q.expectancy)+'</div><div>'+f(q.profitFactor)+'</div><div>'+f(q.proofProgress)+'%</div></div>').join('')}go();setInterval(go,2500)</script>`}
poll();
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');if(req.method==='GET'&&u.pathname==='/health')return out(res,200,{ok:true,version:'OPEN_EDGE_ARENA_V2',live:false,child:child.pid});if(req.method==='GET'&&(u.pathname==='/arena.json'||u.pathname==='/validation.json'))return out(res,200,await combined());if(req.method==='POST'&&u.pathname==='/ingest'){let s='';for await(const c of req)s+=c;let p;try{p=JSON.parse(s)}catch{return out(res,400,{ok:false})}await ingestLocal(p);const q=await inner('/ingest',{method:'POST',headers:{'content-type':'application/json'},body:s});res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,inner:q.status}))}if(req.method==='GET'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});return res.end(page())}out(res,404,{ok:false})}catch(e){fail('server',e);out(res,500,{ok:false,error:String(e?.message||e)})}}).listen(PORT,'0.0.0.0',()=>console.log('OPEN_EDGE_ARENA_V2_READY',JSON.stringify({port:PORT,inner:INNER,live:false,fusionBrains:S.brains.size})));
